# Author: zgliu@cumt.edu.cn
# Affiliation: China University of Mining and Technology
# Open-source release date: 2026-04-20
"""Unit tests for export_evo_report.py.

The fixed timestamps and metric values in this file are synthetic parser and
formatter fixtures. They exist only to verify EVO text parsing and report
layout, and they do not represent benchmark or paper results.
"""

import importlib.util
import pathlib
import shlex
import tempfile
import unittest
from types import SimpleNamespace


SCRIPT_PATH = pathlib.Path(__file__).resolve().parents[1] / "scripts" / "export_evo_report.py"


def load_module_if_exists():
    if not SCRIPT_PATH.exists():
        return None
    spec = importlib.util.spec_from_file_location("export_evo_report", SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class ExportEvoReportTests(unittest.TestCase):
    def test_load_tum_summary_reads_sample_count_and_time_range(self):
        module = load_module_if_exists()
        if module is None:
            self.fail(f"Missing implementation script: {SCRIPT_PATH}")

        with tempfile.TemporaryDirectory(prefix="evo_report_") as temp_dir:
            tum_path = pathlib.Path(temp_dir) / "gt_sensor_world_tum.txt"
            tum_path.write_text(
                "1.000000000 0 0 0 0 0 0 1\n"
                "2.500000000 1 0 0 0 0 0 1\n"
                "4.000000000 2 0 0 0 0 0 1\n"
            )

            summary = module.load_tum_summary(tum_path)

            self.assertEqual(summary.sample_count, 3)
            self.assertEqual(summary.start_time, 1.0)
            self.assertEqual(summary.end_time, 4.0)
            self.assertEqual(summary.duration_sec, 3.0)

    def test_load_tum_summary_ignores_blank_lines_and_comment_headers(self):
        module = load_module_if_exists()
        if module is None:
            self.fail(f"Missing implementation script: {SCRIPT_PATH}")

        with tempfile.TemporaryDirectory(prefix="evo_report_") as temp_dir:
            tum_path = pathlib.Path(temp_dir) / "gt_sensor_world_tum.txt"
            tum_path.write_text(
                "# timestamp x y z qx qy qz qw\n"
                "\n"
                "1.000000000 0 0 0 0 0 0 1\n"
                "  # generated by recorder\n"
                "2.500000000 1 0 0 0 0 0 1\n"
            )

            summary = module.load_tum_summary(tum_path)

            self.assertEqual(summary.sample_count, 2)
            self.assertEqual(summary.start_time, 1.0)
            self.assertEqual(summary.end_time, 2.5)
            self.assertEqual(summary.duration_sec, 1.5)

    def test_load_tum_summary_raises_for_empty_file(self):
        module = load_module_if_exists()
        if module is None:
            self.fail(f"Missing implementation script: {SCRIPT_PATH}")

        with tempfile.TemporaryDirectory(prefix="evo_report_") as temp_dir:
            tum_path = pathlib.Path(temp_dir) / "gt_sensor_world_tum.txt"
            tum_path.write_text("\n# no data\n\n")

            with self.assertRaisesRegex(ValueError, "Empty TUM file"):
                module.load_tum_summary(tum_path)

    def test_parse_metric_summary_extracts_numeric_fields(self):
        module = load_module_if_exists()
        if module is None:
            self.fail(f"Missing implementation script: {SCRIPT_PATH}")

        stdout_text = (
            "APE w.r.t. translation part (m)\n"
            "(with origin alignment)\n\n"
            "       max\t0.004026\n"
            "      mean\t0.002086\n"
            "    median\t0.002223\n"
            "       min\t0.000000\n"
            "      rmse\t0.002228\n"
            "       sse\t0.001896\n"
            "       std\t0.000782\n"
        )

        summary = module.parse_metric_summary(stdout_text)

        self.assertEqual(summary.max_value, 0.004026)
        self.assertEqual(summary.mean, 0.002086)
        self.assertEqual(summary.rmse, 0.002228)

    def test_parse_metric_summary_accepts_scientific_notation_and_signs(self):
        module = load_module_if_exists()
        if module is None:
            self.fail(f"Missing implementation script: {SCRIPT_PATH}")

        stdout_text = (
            "APE w.r.t. translation part (m)\n"
            "\n"
            "       max\t-1.23\n"
            "      mean\t+4.5e-03\n"
            "    median\t1E+2\n"
            "       min\t0\n"
            "      rmse\t2.25E-03\n"
            "       sse\t-3.2e+01\n"
            "       std\t6.5e-04\n"
        )

        summary = module.parse_metric_summary(stdout_text)

        self.assertEqual(summary.max_value, -1.23)
        self.assertEqual(summary.mean, 0.0045)
        self.assertEqual(summary.median, 100.0)
        self.assertEqual(summary.min_value, 0.0)
        self.assertEqual(summary.rmse, 0.00225)
        self.assertEqual(summary.sse, -32.0)
        self.assertEqual(summary.std, 0.00065)

    def test_parse_metric_summary_raises_for_incomplete_stdout(self):
        module = load_module_if_exists()
        if module is None:
            self.fail(f"Missing implementation script: {SCRIPT_PATH}")

        stdout_text = (
            "APE w.r.t. translation part (m)\n"
            "       max\t0.004026\n"
            "      mean\t0.002086\n"
            "    median\t0.002223\n"
        )

        with self.assertRaisesRegex(ValueError, "Missing metric fields"):
            module.parse_metric_summary(stdout_text)

    def test_render_report_uses_chinese_template(self):
        module = load_module_if_exists()
        if module is None:
            self.fail(f"Missing implementation script: {SCRIPT_PATH}")

        # These values intentionally resemble realistic EVO outputs so the
        # formatter is tested against representative text, but they are still
        # synthetic fixtures rather than recorded experiment data.
        tum_summary = module.TumSummary(
            sample_count=382,
            start_time=2435.210714996,
            end_time=2473.309139999,
            duration_sec=38.098425003,
        )
        ape = module.MetricSummary(
            max_value=0.004026,
            mean=0.002086,
            median=0.002223,
            min_value=0.0,
            rmse=0.002228,
            sse=0.001896,
            std=0.000782,
        )
        rpe = module.MetricSummary(
            max_value=0.001879,
            mean=0.000675,
            median=0.000611,
            min_value=0.000201,
            rmse=0.000736,
            sse=0.000206,
            std=0.000293,
        )

        report_text = module.render_report_text(
            run_dir=pathlib.Path("/tmp/sim_run_000"),
            gt_tum_path=pathlib.Path("/tmp/gt.tum"),
            odom_tum_path=pathlib.Path("/tmp/odom.tum"),
            tum_summary=tum_summary,
            ape_summary=ape,
            rpe_summary=rpe,
            traj_plot_path=pathlib.Path("/tmp/traj_overlay_xy.png"),
            ape_plot_path=pathlib.Path("/tmp/ape_trans_error.png"),
            rpe_plot_path=pathlib.Path("/tmp/rpe_trans_1f_error.png"),
            traj_command="evo_traj tum /tmp/gt.tum /tmp/odom.tum --ref /tmp/gt.tum --sync --align_origin --t_max_diff 0.001 --plot_mode xy --save_plot /tmp/traj_overlay_xy.png",
            ape_command="evo_ape tum /tmp/gt.tum /tmp/odom.tum --align_origin -r trans_part --t_max_diff 0.001 --save_plot /tmp/ape_trans_error.png",
            rpe_command="evo_rpe tum /tmp/gt.tum /tmp/odom.tum --align_origin -r trans_part -u f -d 1 --t_max_diff 0.001 --save_plot /tmp/rpe_trans_1f_error.png",
            generated_at="2026-03-31T02:00:00",
            t_max_diff=0.001,
            alignment_mode="origin_alignment",
            rpe_delta=1,
            notes=["test note"],
        )

        self.assertIn("EVO Trajectory Report", report_text)
        self.assertIn("1. Basic Info", report_text)
        self.assertIn("Run Dir: /tmp/sim_run_000", report_text)
        self.assertIn("Generated: 2026-03-31T02:00:00", report_text)
        self.assertIn("t_max_diff：0.001000 s", report_text)
        self.assertIn("Align Mode: origin_alignment", report_text)
        self.assertIn("RPE delta：1", report_text)
        self.assertIn("2. Input Trajectories", report_text)
        self.assertIn("GT TUM：/tmp/gt.tum", report_text)
        self.assertIn("Odom TUM: /tmp/odom.tum", report_text)
        self.assertIn("3. Trajectory Summary", report_text)
        self.assertIn("TUM Samples: 382", report_text)
        self.assertIn("Duration: 38.098425003 s", report_text)
        self.assertIn("4. APE Translation Error", report_text)
        self.assertIn("5. RPE Translation Error", report_text)
        self.assertIn("SSE：0.001896 m^2", report_text)
        self.assertIn("SSE：0.000206 m^2", report_text)
        self.assertIn("6. Figures", report_text)
        self.assertIn("Trajectory Plot: /tmp/traj_overlay_xy.png", report_text)
        self.assertIn("APE Plot: /tmp/ape_trans_error.png", report_text)
        self.assertIn("RPE Plot: /tmp/rpe_trans_1f_error.png", report_text)
        self.assertIn("7. Repro Commands", report_text)
        self.assertIn("The commands below reproduce the exported outputs.", report_text)
        self.assertIn(
            "Trajectory Cmd: evo_traj tum /tmp/gt.tum /tmp/odom.tum --ref /tmp/gt.tum --sync --align_origin --t_max_diff 0.001 --plot_mode xy --save_plot /tmp/traj_overlay_xy.png",
            report_text,
        )
        self.assertIn(
            "APE Cmd: evo_ape tum /tmp/gt.tum /tmp/odom.tum --align_origin -r trans_part --t_max_diff 0.001 --save_plot /tmp/ape_trans_error.png",
            report_text,
        )
        self.assertIn(
            "RPE Cmd: evo_rpe tum /tmp/gt.tum /tmp/odom.tum --align_origin -r trans_part -u f -d 1 --t_max_diff 0.001 --save_plot /tmp/rpe_trans_1f_error.png",
            report_text,
        )
        self.assertIn("RMSE：0.002228 m", report_text)
        self.assertIn("8. Notes", report_text)
        self.assertNotIn("3. APE Cmd", report_text)
        self.assertNotIn("5. RPE Cmd", report_text)
        self.assertNotIn("7. Param Notes", report_text)

    def test_run_evo_command_sets_headless_backend_and_returns_stdout(self):
        module = load_module_if_exists()
        if module is None:
            self.fail(f"Missing implementation script: {SCRIPT_PATH}")

        captured = {}

        def fake_run(cmd, check, capture_output, text, env):
            captured["cmd"] = cmd
            captured["check"] = check
            captured["capture_output"] = capture_output
            captured["text"] = text
            captured["env"] = env
            return SimpleNamespace(stdout="fake stdout\n", stderr="")

        original_run = module.subprocess.run
        module.subprocess.run = fake_run
        try:
            stdout_text = module.run_evo_command(
                ["evo_ape", "tum", "/tmp/gt.tum", "/tmp/odom.tum", "--align_origin"]
            )
        finally:
            module.subprocess.run = original_run

        self.assertEqual(stdout_text, "fake stdout\n")
        self.assertEqual(captured["cmd"][0], "evo_ape")
        self.assertTrue(captured["check"])
        self.assertTrue(captured["capture_output"])
        self.assertTrue(captured["text"])
        self.assertEqual(captured["env"]["MPLBACKEND"], "Agg")

    def test_build_ape_command_uses_alignment_and_plot_path(self):
        module = load_module_if_exists()
        if module is None:
            self.fail(f"Missing implementation script: {SCRIPT_PATH}")

        cmd = module.build_ape_command(
            gt_tum_path=pathlib.Path("/tmp/gt.tum"),
            odom_tum_path=pathlib.Path("/tmp/odom.tum"),
            output_png=pathlib.Path("/tmp/ape_trans_error.png"),
            t_max_diff=0.001,
        )

        self.assertEqual(
            cmd,
            [
                "evo_ape",
                "tum",
                "/tmp/gt.tum",
                "/tmp/odom.tum",
                "--align_origin",
                "-r",
                "trans_part",
                "--t_max_diff",
                "0.001",
                "--save_plot",
                "/tmp/ape_trans_error.png",
            ],
        )

    def test_build_rpe_command_uses_delta_and_plot_path(self):
        module = load_module_if_exists()
        if module is None:
            self.fail(f"Missing implementation script: {SCRIPT_PATH}")

        cmd = module.build_rpe_command(
            gt_tum_path=pathlib.Path("/tmp/gt.tum"),
            odom_tum_path=pathlib.Path("/tmp/odom.tum"),
            output_png=pathlib.Path("/tmp/rpe_trans_1f_error.png"),
            t_max_diff=0.001,
            delta=1,
        )

        self.assertEqual(
            cmd,
            [
                "evo_rpe",
                "tum",
                "/tmp/gt.tum",
                "/tmp/odom.tum",
                "--align_origin",
                "-r",
                "trans_part",
                "-u",
                "f",
                "-d",
                "1",
                "--t_max_diff",
                "0.001",
                "--save_plot",
                "/tmp/rpe_trans_1f_error.png",
            ],
        )

    def test_build_traj_command_uses_sync_and_align_origin(self):
        module = load_module_if_exists()
        if module is None:
            self.fail(f"Missing implementation script: {SCRIPT_PATH}")

        cmd = module.build_traj_command(
            gt_tum_path=pathlib.Path("/tmp/gt.tum"),
            odom_tum_path=pathlib.Path("/tmp/odom.tum"),
            output_png=pathlib.Path("/tmp/traj_overlay_xy.png"),
            t_max_diff=0.001,
        )

        self.assertEqual(cmd[0], "evo_traj")
        self.assertIn("--sync", cmd)
        self.assertIn("--align_origin", cmd)
        self.assertIn("--save_plot", cmd)
        self.assertEqual(
            cmd,
            [
                "evo_traj",
                "tum",
                "/tmp/gt.tum",
                "/tmp/odom.tum",
                "--ref",
                "/tmp/gt.tum",
                "--sync",
                "--align_origin",
                "--t_max_diff",
                "0.001",
                "--plot_mode",
                "xy",
                "--save_plot",
                "/tmp/traj_overlay_xy.png",
            ],
        )

    def test_command_text_uses_shell_style_quoting(self):
        module = load_module_if_exists()
        if module is None:
            self.fail(f"Missing implementation script: {SCRIPT_PATH}")

        command = [
            "evo_ape",
            "tum",
            "/tmp/run dir/trajectory/gt file.tum",
            "/tmp/run dir/trajectory/odom&raw.tum",
            "--save_plot",
            "/tmp/run dir/analysis/evo/ape plot.png",
        ]

        self.assertEqual(module._command_to_text(command), shlex.join(command))
        self.assertIn("'", module._command_to_text(command))

    def test_export_evo_report_writes_report_commands_stdout_and_png_paths(self):
        module = load_module_if_exists()
        if module is None:
            self.fail(f"Missing implementation script: {SCRIPT_PATH}")

        with tempfile.TemporaryDirectory(prefix="evo report run_") as temp_dir:
            run_dir = pathlib.Path(temp_dir) / "sim run 000"
            trajectory_dir = run_dir / "trajectory"
            trajectory_dir.mkdir(parents=True)
            (trajectory_dir / "gt_sensor_world_tum.txt").write_text(
                "1.000000000 0 0 0 0 0 0 1\n"
                "2.000000000 0 0 0 0 0 0 1\n"
            )
            (trajectory_dir / "odom_raw_tum.txt").write_text(
                "1.000000000 0.1 0 0 0 0 0 1\n"
                "2.000000000 0.2 0 0 0 0 0 1\n"
            )

            stdout_by_tool = {
                "evo_ape": (
                    "       max\t0.1\n"
                    "      mean\t0.2\n"
                    "    median\t0.3\n"
                    "       min\t0.0\n"
                    "      rmse\t0.4\n"
                    "       sse\t0.5\n"
                    "       std\t0.6\n"
                ),
                "evo_rpe": (
                    "       max\t0.01\n"
                    "      mean\t0.02\n"
                    "    median\t0.03\n"
                    "       min\t0.0\n"
                    "      rmse\t0.04\n"
                    "       sse\t0.05\n"
                    "       std\t0.06\n"
                ),
                "evo_traj": "trajectory ok\n",
            }

            def fake_run_evo_command(cmd):
                output_png = pathlib.Path(cmd[-1])
                if cmd[0] == "evo_traj":
                    output_png.with_name(f"{output_png.stem}_trajectories.png").write_bytes(b"traj")
                elif cmd[0] == "evo_ape":
                    output_png.with_name(f"{output_png.stem}_raw.png").write_bytes(b"ape-raw")
                    output_png.with_name(f"{output_png.stem}_map.png").write_bytes(b"ape-map")
                elif cmd[0] == "evo_rpe":
                    output_png.with_name(f"{output_png.stem}_raw.png").write_bytes(b"rpe-raw")
                    output_png.with_name(f"{output_png.stem}_map.png").write_bytes(b"rpe-map")
                return stdout_by_tool[cmd[0]]

            original_runner = module.run_evo_command
            module.run_evo_command = fake_run_evo_command
            try:
                outputs = module.export_evo_report(run_dir)
            finally:
                module.run_evo_command = original_runner

            self.assertTrue(outputs.report_txt.is_file())
            self.assertTrue(outputs.commands_txt.is_file())
            self.assertTrue(outputs.ape_stdout_txt.is_file())
            self.assertTrue(outputs.rpe_stdout_txt.is_file())
            self.assertTrue(outputs.traj_plot_png.is_file())
            self.assertTrue(outputs.ape_plot_png.is_file())
            self.assertTrue(outputs.rpe_plot_png.is_file())
            self.assertIn("EVO Trajectory Report", outputs.report_txt.read_text())
            self.assertIn("traj_overlay_xy.png", outputs.report_txt.read_text())
            self.assertIn("ape_trans_error.png", outputs.report_txt.read_text())
            self.assertIn("rpe_trans_1f_error.png", outputs.report_txt.read_text())
            self.assertIn("evo_ape", outputs.commands_txt.read_text())
            self.assertIn("'", outputs.commands_txt.read_text())
            self.assertIn("'", outputs.report_txt.read_text())
            self.assertTrue(outputs.commands_txt.read_text().startswith("# Repro Commands"))
            self.assertIn("# The commands below use the final output paths.", outputs.commands_txt.read_text())
            self.assertEqual(outputs.ape_stdout_txt.read_text(), stdout_by_tool["evo_ape"])
            self.assertEqual(outputs.rpe_stdout_txt.read_text(), stdout_by_tool["evo_rpe"])

    def test_export_evo_report_uses_delta_specific_rpe_artifacts(self):
        module = load_module_if_exists()
        if module is None:
            self.fail(f"Missing implementation script: {SCRIPT_PATH}")

        with tempfile.TemporaryDirectory(prefix="evo_report_delta_") as temp_dir:
            run_dir = pathlib.Path(temp_dir) / "sim_run_000"
            trajectory_dir = run_dir / "trajectory"
            output_dir = run_dir / "analysis" / "evo"
            trajectory_dir.mkdir(parents=True)
            output_dir.mkdir(parents=True)
            (trajectory_dir / "gt_sensor_world_tum.txt").write_text(
                "1.000000000 0 0 0 0 0 0 1\n"
                "2.000000000 0 0 0 0 0 0 1\n"
            )
            (trajectory_dir / "odom_raw_tum.txt").write_text(
                "1.000000000 0.1 0 0 0 0 0 1\n"
                "2.000000000 0.2 0 0 0 0 0 1\n"
            )
            (output_dir / "rpe_trans_1f_stdout.txt").write_text("stale rpe stdout\n")
            (output_dir / "rpe_trans_1f_error.png").write_bytes(b"stale-rpe-plot")

            stdout_by_tool = {
                "evo_ape": (
                    "       max\t0.1\n"
                    "      mean\t0.2\n"
                    "    median\t0.3\n"
                    "       min\t0.0\n"
                    "      rmse\t0.4\n"
                    "       sse\t0.5\n"
                    "       std\t0.6\n"
                ),
                "evo_rpe": (
                    "       max\t0.01\n"
                    "      mean\t0.02\n"
                    "    median\t0.03\n"
                    "       min\t0.0\n"
                    "      rmse\t0.04\n"
                    "       sse\t0.05\n"
                    "       std\t0.06\n"
                ),
                "evo_traj": "trajectory ok\n",
            }

            def fake_run_evo_command(cmd):
                output_png = pathlib.Path(cmd[-1])
                if cmd[0] == "evo_traj":
                    output_png.with_name(f"{output_png.stem}_trajectories.png").write_bytes(b"traj")
                elif cmd[0] == "evo_ape":
                    output_png.with_name(f"{output_png.stem}_raw.png").write_bytes(b"ape-raw")
                    output_png.with_name(f"{output_png.stem}_map.png").write_bytes(b"ape-map")
                elif cmd[0] == "evo_rpe":
                    output_png.with_name(f"{output_png.stem}_raw.png").write_bytes(b"rpe-raw")
                    output_png.with_name(f"{output_png.stem}_map.png").write_bytes(b"rpe-map")
                return stdout_by_tool[cmd[0]]

            original_runner = module.run_evo_command
            module.run_evo_command = fake_run_evo_command
            try:
                outputs = module.export_evo_report(run_dir, rpe_delta=5)
            finally:
                module.run_evo_command = original_runner

            self.assertEqual(outputs.rpe_stdout_txt.name, "rpe_trans_5f_stdout.txt")
            self.assertEqual(outputs.rpe_plot_png.name, "rpe_trans_5f_error.png")
            self.assertTrue(outputs.rpe_stdout_txt.is_file())
            self.assertTrue(outputs.rpe_plot_png.is_file())
            self.assertEqual(outputs.rpe_stdout_txt.name, "rpe_trans_5f_stdout.txt")
            self.assertIn("rpe_trans_5f_error.png", outputs.report_txt.read_text())
            self.assertFalse((output_dir / "rpe_trans_1f_stdout.txt").exists())
            self.assertFalse((output_dir / "rpe_trans_1f_error.png").exists())

    def test_export_evo_report_keeps_previous_outputs_when_rerun_fails(self):
        module = load_module_if_exists()
        if module is None:
            self.fail(f"Missing implementation script: {SCRIPT_PATH}")

        with tempfile.TemporaryDirectory(prefix="evo_report_atomic_") as temp_dir:
            run_dir = pathlib.Path(temp_dir) / "sim_run_000"
            trajectory_dir = run_dir / "trajectory"
            output_dir = run_dir / "analysis" / "evo"
            trajectory_dir.mkdir(parents=True)
            output_dir.mkdir(parents=True)
            (trajectory_dir / "gt_sensor_world_tum.txt").write_text(
                "1.000000000 0 0 0 0 0 0 1\n"
                "2.000000000 0 0 0 0 0 0 1\n"
            )
            (trajectory_dir / "odom_raw_tum.txt").write_text(
                "1.000000000 0.1 0 0 0 0 0 1\n"
                "2.000000000 0.2 0 0 0 0 0 1\n"
            )
            (output_dir / "report.txt").write_text("previous report\n")
            (output_dir / "commands.txt").write_text("previous commands\n")
            (output_dir / "ape_trans_stdout.txt").write_text("previous ape stdout\n")
            (output_dir / "rpe_trans_1f_stdout.txt").write_text("previous rpe stdout\n")

            def fake_run_evo_command(cmd):
                if cmd[0] == "evo_traj":
                    plot_path = pathlib.Path(cmd[-1])
                    plot_path.with_name(f"{plot_path.stem}_trajectories.png").write_bytes(b"traj")
                    return "trajectory ok\n"
                raise RuntimeError("simulated evo failure")

            original_runner = module.run_evo_command
            module.run_evo_command = fake_run_evo_command
            try:
                with self.assertRaisesRegex(RuntimeError, "simulated evo failure"):
                    module.export_evo_report(run_dir)
            finally:
                module.run_evo_command = original_runner

            self.assertEqual((output_dir / "report.txt").read_text(), "previous report\n")
            self.assertEqual((output_dir / "commands.txt").read_text(), "previous commands\n")
            self.assertEqual((output_dir / "ape_trans_stdout.txt").read_text(), "previous ape stdout\n")
            self.assertEqual((output_dir / "rpe_trans_1f_stdout.txt").read_text(), "previous rpe stdout\n")
            self.assertFalse((output_dir / "traj_overlay_xy.png").exists())


if __name__ == "__main__":
    unittest.main(verbosity=2)
