common:
  lid_topic: "/livox/lidar"
  imu_topic: "/livox/imu"
  time_sync_en: false
  time_offset_lidar_to_imu:
    0.0

preprocess:
  lidar_type: 1
  scan_line: 4
  blind: 0.2

mapping:
  acc_cov: 0.1
  gyr_cov: 0.1
  b_acc_cov: 0.0001
  b_gyr_cov: 0.0001
  fov_degree: 360
  det_range: 100.0
  extrinsic_est_en: false
  extrinsic_T: [0.038, 0.0, 0.01]
  extrinsic_R: [1, 0, 0, 0, 1, 0, 0, 0, 1]

publish:
  path_en: true
  scan_publish_en: true
  dense_publish_en: true
  scan_bodyframe_pub_en: true

pcd_save:
  pcd_save_en: false
  interval:
    -1
